# Generated by Django 5.0.6 on 2024-05-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='task_details',
            field=models.TextField(max_length=1000),
        ),
    ]
