# Generated by Django 5.0.6 on 2024-05-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_todo_task_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('in_progress', 'In Progress'), ('Completed', 'Completed')], max_length=20),
        ),
    ]
