# Generated by Django 5.0.6 on 2024-05-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('in_progress', 'In Progress'), ('complete', 'Complete')], max_length=20),
        ),
    ]
